### ISSUE TITLE
Some Timelines aren't working (probably DB error)

### ISSUE THREAD

**Issue by Philipnah** [ITU-BDSA23-GROUP5/Chirp#42]
Theory: It's probably due to not having 37 cheeps or more, and therefore a database error probably occurs, returning no cheeps, and the timeline is displayed as empty.

Acceptance criteria:
- Clicking on a users username on the public timeline, should show the users timeline with all their cheeps in paginated format.
- Should not show an empty timeline for a user who has posted on the public timeline

**Comment by LavenderPlush** [comment]
Pagination was 0-indexed in the service, and is now changed to take page number - 1
